// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thcntaydotvtktjqyadi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoY250YXlkb3R2dGt0anF5YWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDM0MDcsImV4cCI6MjA3ODExOTQwN30.2FBOSz-xoE5pjGZ3KP9N1BFIeMS53q-kjlbphipPeJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});